
// Generated by Cadence Encounter(R) RTL Compiler v07.20-s009_1

module PORTS(ports_sfr_PXEN_i, ports_sfr_PX_i, ports_sfr_PX_o,
     y_portX_i, en_portX_o, a_portX_o);
  input [7:0] ports_sfr_PXEN_i, ports_sfr_PX_i, y_portX_i;
  output [7:0] ports_sfr_PX_o, en_portX_o, a_portX_o;
  wire [7:0] ports_sfr_PXEN_i, ports_sfr_PX_i, y_portX_i;
  wire [7:0] ports_sfr_PX_o, en_portX_o, a_portX_o;
  assign a_portX_o[0] = ports_sfr_PX_i[0];
  assign a_portX_o[1] = ports_sfr_PX_i[1];
  assign a_portX_o[2] = ports_sfr_PX_i[2];
  assign a_portX_o[3] = ports_sfr_PX_i[3];
  assign a_portX_o[4] = ports_sfr_PX_i[4];
  assign a_portX_o[5] = ports_sfr_PX_i[5];
  assign a_portX_o[6] = ports_sfr_PX_i[6];
  assign a_portX_o[7] = ports_sfr_PX_i[7];
  assign ports_sfr_PX_o[0] = y_portX_i[0];
  assign ports_sfr_PX_o[1] = y_portX_i[1];
  assign ports_sfr_PX_o[2] = y_portX_i[2];
  assign ports_sfr_PX_o[3] = y_portX_i[3];
  assign ports_sfr_PX_o[4] = y_portX_i[4];
  assign ports_sfr_PX_o[5] = y_portX_i[5];
  assign ports_sfr_PX_o[6] = y_portX_i[6];
  assign ports_sfr_PX_o[7] = y_portX_i[7];
  not g51 (en_portX_o[1], ports_sfr_PXEN_i[1]);
  not g50 (en_portX_o[2], ports_sfr_PXEN_i[2]);
  not g49 (en_portX_o[3], ports_sfr_PXEN_i[3]);
  not g48 (en_portX_o[4], ports_sfr_PXEN_i[4]);
  not g47 (en_portX_o[5], ports_sfr_PXEN_i[5]);
  not g46 (en_portX_o[6], ports_sfr_PXEN_i[6]);
  not g45 (en_portX_o[7], ports_sfr_PXEN_i[7]);
  not g52 (en_portX_o[0], ports_sfr_PXEN_i[0]);
endmodule

module PORT_TOP(ports_sfr_P0EN_i, ports_sfr_P1EN_i, ports_sfr_P2EN_i,
     ports_sfr_P3EN_i, ports_sfr_P0_i, ports_sfr_P1_i, ports_sfr_P2_i,
     ports_sfr_P3_i, ports_sfr_P4_i, ports_sfr_P0_o, ports_sfr_P1_o,
     ports_sfr_P2_o, ports_sfr_P3_o, y_port0_i, y_port1_i, y_port2_i,
     y_port3_i, en_port0_o, en_port1_o, en_port2_o, en_port3_o,
     a_port0_o, a_port1_o, a_port2_o, a_port3_o, a_port4_o);
  input [7:0] ports_sfr_P0EN_i, ports_sfr_P1EN_i, ports_sfr_P2EN_i,
       ports_sfr_P3EN_i, ports_sfr_P0_i, ports_sfr_P1_i,
       ports_sfr_P2_i, ports_sfr_P3_i, ports_sfr_P4_i, y_port0_i,
       y_port1_i, y_port2_i, y_port3_i;
  output [7:0] ports_sfr_P0_o, ports_sfr_P1_o, ports_sfr_P2_o,
       ports_sfr_P3_o, en_port0_o, en_port1_o, en_port2_o, en_port3_o,
       a_port0_o, a_port1_o, a_port2_o, a_port3_o, a_port4_o;
  wire [7:0] ports_sfr_P0EN_i, ports_sfr_P1EN_i, ports_sfr_P2EN_i,
       ports_sfr_P3EN_i, ports_sfr_P0_i, ports_sfr_P1_i,
       ports_sfr_P2_i, ports_sfr_P3_i, ports_sfr_P4_i, y_port0_i,
       y_port1_i, y_port2_i, y_port3_i;
  wire [7:0] ports_sfr_P0_o, ports_sfr_P1_o, ports_sfr_P2_o,
       ports_sfr_P3_o, en_port0_o, en_port1_o, en_port2_o, en_port3_o,
       a_port0_o, a_port1_o, a_port2_o, a_port3_o, a_port4_o;
  assign a_port4_o[0] = ports_sfr_P4_i[0];
  assign a_port4_o[1] = ports_sfr_P4_i[1];
  assign a_port4_o[2] = ports_sfr_P4_i[2];
  assign a_port4_o[3] = ports_sfr_P4_i[3];
  assign a_port4_o[4] = ports_sfr_P4_i[4];
  assign a_port4_o[5] = ports_sfr_P4_i[5];
  assign a_port4_o[6] = ports_sfr_P4_i[6];
  assign a_port4_o[7] = ports_sfr_P4_i[7];
  PORTS port0(.ports_sfr_PXEN_i (ports_sfr_P0EN_i), .ports_sfr_PX_i
       (ports_sfr_P0_i), .ports_sfr_PX_o (ports_sfr_P0_o), .y_portX_i
       (y_port0_i), .en_portX_o (en_port0_o), .a_portX_o (a_port0_o));
  PORTS port1(.ports_sfr_PXEN_i (ports_sfr_P1EN_i), .ports_sfr_PX_i
       (ports_sfr_P1_i), .ports_sfr_PX_o (ports_sfr_P1_o), .y_portX_i
       (y_port1_i), .en_portX_o (en_port1_o), .a_portX_o (a_port1_o));
  PORTS port2(.ports_sfr_PXEN_i (ports_sfr_P2EN_i), .ports_sfr_PX_i
       (ports_sfr_P2_i), .ports_sfr_PX_o (ports_sfr_P2_o), .y_portX_i
       (y_port2_i), .en_portX_o (en_port2_o), .a_portX_o (a_port2_o));
  PORTS port3(.ports_sfr_PXEN_i (ports_sfr_P3EN_i), .ports_sfr_PX_i
       (ports_sfr_P3_i), .ports_sfr_PX_o (ports_sfr_P3_o), .y_portX_i
       (y_port3_i), .en_portX_o (en_port3_o), .a_portX_o (a_port3_o));
endmodule

