
# NC-Sim Command File
# TOOL:	ncsim	06.10-p001
#
#
# You can restore this configuration with:
#
#     ncsim -gui serial_top_tb_mode2 -input /home/student/EMC08/digital_A/serial/design/rtl_v/restore_mode2_presentation.tcl
#

set tcl_prompt1 {puts -nonewline "ncsim> "}
set tcl_prompt2 {puts -nonewline "> "}
set vlog_format %h
set vhdl_format %v
set real_precision 6
set display_unit auto
set time_unit module
set heap_garbage_size -200
set heap_garbage_time 0
set assert_report_level note
set assert_stop_level error
set autoscope yes
set assert_1164_warnings yes
set pack_assert_off {}
set severity_pack_assert_off {note warning}
set assert_output_stop_level failed
set tcl_debug_level 0
set relax_path_name 0
set vhdl_vcdmap XX01ZX01X
set intovf_severity_level ERROR
set probe_screen_format 0
set rangecnst_severity_level ERROR
set textio_severity_level ERROR
set vital_timing_checks_on 1
set vlog_code_show_force 0
set assert_count_attempts 0
database -open -shm -into waves.shm waves -default
probe -create -database waves serial_top_tb_mode2.serial_top_tb_mode2.BR_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.BR_TRANS_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.CLEAR_COUNT_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.CLOCK_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.DATA_EN_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.DATA_MODE0_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.DATA_SBUF_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.DATA_TX_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.P3EN_0_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.P3EN_1_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.RECEIVE_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.RESET_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.RXD_DATA_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SBUF_RX_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SCON0_RI_I_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SCON0_RI_O_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SCON1_TI_I_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SCON1_TI_O_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SCON2_RB8_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SCON3_TB8_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SCON4_REN_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SCON7_MODE_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SEND_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.SERIAL_TX_INTERNAL serial_top_tb_mode2.serial_top_tb_mode2.p3en_0_temp1 serial_top_tb_mode2.serial_top_tb_mode2.p3en_0_temp2 serial_top_tb_mode2.serial_top_tb_mode2.p3en_1_temp1 serial_top_tb_mode2.serial_top_tb_mode2.p3en_1_temp2 serial_top_tb_mode2.serial_top_tb_mode2.serial_br_i serial_top_tb_mode2.serial_top_tb_mode2.serial_br_trans_i serial_top_tb_mode2.serial_top_tb_mode2.serial_clear_count_o serial_top_tb_mode2.serial_top_tb_mode2.serial_clock_i serial_top_tb_mode2.serial_top_tb_mode2.serial_data_sbuf_i serial_top_tb_mode2.serial_top_tb_mode2.serial_data_sbuf_o serial_top_tb_mode2.serial_top_tb_mode2.serial_p3_0_i serial_top_tb_mode2.serial_top_tb_mode2.serial_p3_0_o serial_top_tb_mode2.serial_top_tb_mode2.serial_p3_1_o serial_top_tb_mode2.serial_top_tb_mode2.serial_p3en_0_o serial_top_tb_mode2.serial_top_tb_mode2.serial_p3en_1_o serial_top_tb_mode2.serial_top_tb_mode2.serial_reset_i_b serial_top_tb_mode2.serial_top_tb_mode2.serial_scon0_ri_i serial_top_tb_mode2.serial_top_tb_mode2.serial_scon0_ri_o serial_top_tb_mode2.serial_top_tb_mode2.serial_scon1_ti_i serial_top_tb_mode2.serial_top_tb_mode2.serial_scon1_ti_o serial_top_tb_mode2.serial_top_tb_mode2.serial_scon2_rb8_o serial_top_tb_mode2.serial_top_tb_mode2.serial_scon3_tb8_i serial_top_tb_mode2.serial_top_tb_mode2.serial_scon4_ren_i serial_top_tb_mode2.serial_top_tb_mode2.serial_scon7_sm0_i serial_top_tb_mode2.serial_top_tb_mode2.serial_serial_tx_i
probe -create -database waves serial_top_tb_mode2.serial_top_tb_mode2.serial_rx_block.serial_rx_detector.counter

simvision -input /home/student/EMC08/digital_A/serial/design/rtl_v/restore_mode2_presentation.tcl.svcf
