
// Generated by Cadence Encounter(R) RTL Compiler v07.20-s009_1

module increment_unsigned_202(A, CI, Z);
  input [14:0] A;
  input CI;
  output [15:0] Z;
  wire [14:0] A;
  wire CI;
  wire [15:0] Z;
  wire n_0, n_2, n_4, n_6, n_8, n_10, n_12, n_14;
  wire n_16, n_18, n_20, n_23, n_24;
  assign Z[0] = 1'b0;
  assign Z[15] = 1'b0;
  EN2JIX0 g43(.A (n_24), .B (A[14]), .Q (Z[14]));
  EO2JIX0 g44(.A (n_23), .B (A[13]), .Q (Z[13]));
  NA2JIX0 g45(.A (n_23), .B (A[13]), .Q (n_24));
  HAJIX0 g46(.A (n_20), .B (A[12]), .S (Z[12]), .CO (n_23));
  HAJIX0 g47(.A (n_18), .B (A[11]), .S (Z[11]), .CO (n_20));
  HAJIX0 g48(.A (n_16), .B (A[10]), .S (Z[10]), .CO (n_18));
  HAJIX0 g49(.A (n_14), .B (A[9]), .S (Z[9]), .CO (n_16));
  HAJIX0 g50(.A (n_12), .B (A[8]), .S (Z[8]), .CO (n_14));
  HAJIX0 g51(.A (n_10), .B (A[7]), .S (Z[7]), .CO (n_12));
  HAJIX0 g52(.A (n_8), .B (A[6]), .S (Z[6]), .CO (n_10));
  HAJIX0 g53(.A (n_6), .B (A[5]), .S (Z[5]), .CO (n_8));
  HAJIX0 g54(.A (n_4), .B (A[4]), .S (Z[4]), .CO (n_6));
  HAJIX0 g55(.A (n_2), .B (A[3]), .S (Z[3]), .CO (n_4));
  HAJIX0 g56(.A (n_0), .B (A[2]), .S (Z[2]), .CO (n_2));
  HAJIX0 g57(.A (A[0]), .B (A[1]), .S (Z[1]), .CO (n_0));
endmodule

module increment_unsigned_204(A, CI, Z);
  input [14:0] A;
  input CI;
  output [15:0] Z;
  wire [14:0] A;
  wire CI;
  wire [15:0] Z;
  wire n_0, n_2, n_4, n_6, n_8, n_10, n_12, n_14;
  wire n_16, n_18, n_20, n_23, n_24;
  assign Z[0] = 1'b0;
  assign Z[15] = 1'b0;
  EN2JIX0 g43(.A (n_24), .B (A[14]), .Q (Z[14]));
  EO2JIX0 g44(.A (n_23), .B (A[13]), .Q (Z[13]));
  NA2JIX0 g45(.A (n_23), .B (A[13]), .Q (n_24));
  HAJIX0 g46(.A (n_20), .B (A[12]), .S (Z[12]), .CO (n_23));
  HAJIX0 g47(.A (n_18), .B (A[11]), .S (Z[11]), .CO (n_20));
  HAJIX0 g48(.A (n_16), .B (A[10]), .S (Z[10]), .CO (n_18));
  HAJIX0 g49(.A (n_14), .B (A[9]), .S (Z[9]), .CO (n_16));
  HAJIX0 g50(.A (n_12), .B (A[8]), .S (Z[8]), .CO (n_14));
  HAJIX0 g51(.A (n_10), .B (A[7]), .S (Z[7]), .CO (n_12));
  HAJIX0 g52(.A (n_8), .B (A[6]), .S (Z[6]), .CO (n_10));
  HAJIX0 g53(.A (n_6), .B (A[5]), .S (Z[5]), .CO (n_8));
  HAJIX0 g54(.A (n_4), .B (A[4]), .S (Z[4]), .CO (n_6));
  HAJIX0 g55(.A (n_2), .B (A[3]), .S (Z[3]), .CO (n_4));
  HAJIX0 g56(.A (n_0), .B (A[2]), .S (Z[2]), .CO (n_2));
  HAJIX0 g57(.A (A[0]), .B (A[1]), .S (Z[1]), .CO (n_0));
endmodule

module baud_rate(system_clk_i, system_rst_i_b, baud_rate_scon_sm0_i,
     baud_rate_scon_sm1_i, baud_rate_scon_sm2_i, baud_rate_pcon_smod_i,
     baud_rate_pcon_rs232_i, baud_rate_start_cm_i,
     baud_rate_clear_counter_i, baud_rate_cm_o, baud_rate_br_trans_o,
     baud_rate_br_o);
  input system_clk_i, system_rst_i_b, baud_rate_scon_sm0_i,
       baud_rate_scon_sm1_i, baud_rate_scon_sm2_i,
       baud_rate_pcon_smod_i, baud_rate_pcon_rs232_i,
       baud_rate_start_cm_i, baud_rate_clear_counter_i;
  output baud_rate_cm_o, baud_rate_br_trans_o, baud_rate_br_o;
  wire system_clk_i, system_rst_i_b, baud_rate_scon_sm0_i,
       baud_rate_scon_sm1_i, baud_rate_scon_sm2_i,
       baud_rate_pcon_smod_i, baud_rate_pcon_rs232_i,
       baud_rate_start_cm_i, baud_rate_clear_counter_i;
  wire baud_rate_cm_o, baud_rate_br_trans_o, baud_rate_br_o;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       \baud_rate_RS232_counter[0] , \baud_rate_RS232_counter[1] ,
       \baud_rate_RS232_counter[2] , \baud_rate_RS232_counter[3] ;
  wire \baud_rate_RS232_counter[4] , \baud_rate_RS232_counter[5] ,
       \baud_rate_RS232_counter[6] , \baud_rate_RS232_counter[7] ,
       \baud_rate_RS232_counter[8] , \baud_rate_RS232_counter[9] ,
       \baud_rate_RS232_counter[10] , \baud_rate_RS232_counter[11] ;
  wire \baud_rate_RS232_counter[12] , \baud_rate_RS232_counter[13] ,
       \baud_rate_RS232_counter[14] , \baud_rate_RS232_trans_counter[0]
       , \baud_rate_RS232_trans_counter[1] ,
       \baud_rate_RS232_trans_counter[2] ,
       \baud_rate_RS232_trans_counter[3] ,
       \baud_rate_RS232_trans_counter[4] ;
  wire \baud_rate_RS232_trans_counter[5] ,
       \baud_rate_RS232_trans_counter[6] ,
       \baud_rate_RS232_trans_counter[7] ,
       \baud_rate_RS232_trans_counter[8] ,
       \baud_rate_RS232_trans_counter[9] ,
       \baud_rate_RS232_trans_counter[10] ,
       \baud_rate_RS232_trans_counter[11] ,
       \baud_rate_RS232_trans_counter[12] ;
  wire \baud_rate_RS232_trans_counter[13] ,
       \baud_rate_RS232_trans_counter[14] , \baud_rate_RS232_width[1] ,
       \baud_rate_RS232_width[2] , \baud_rate_RS232_width[3] ,
       \baud_rate_RS232_width[4] , \baud_rate_RS232_width[5] ,
       \baud_rate_RS232_width[7] ;
  wire \baud_rate_RS232_width[8] , \baud_rate_RS232_width[9] ,
       \baud_rate_RS232_width[10] , \baud_rate_RS232_width[11] ,
       \baud_rate_RS232_width[12] , \baud_rate_RS232_width[13] ,
       \baud_rate_RS232_width[14] , \baud_rate_counter[0] ;
  wire \baud_rate_counter[1] , \baud_rate_counter[2] ,
       \baud_rate_counter[3] , \baud_rate_counter[4] ,
       baud_rate_machine_cycle_start, \baud_rate_trans_counter[0] ,
       \baud_rate_width[0] , \baud_rate_width[1] ;
  wire \baud_rate_width[2] , \baud_rate_width[3] , \baud_rate_width[4]
       , \baud_rate_width[5] , n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_193;
  increment_unsigned_202 inc_add_216_79(.A
       ({\baud_rate_RS232_trans_counter[14] ,
       \baud_rate_RS232_trans_counter[13] ,
       \baud_rate_RS232_trans_counter[12] ,
       \baud_rate_RS232_trans_counter[11] ,
       \baud_rate_RS232_trans_counter[10] ,
       \baud_rate_RS232_trans_counter[9] ,
       \baud_rate_RS232_trans_counter[8] ,
       \baud_rate_RS232_trans_counter[7] ,
       \baud_rate_RS232_trans_counter[6] ,
       \baud_rate_RS232_trans_counter[5] ,
       \baud_rate_RS232_trans_counter[4] ,
       \baud_rate_RS232_trans_counter[3] ,
       \baud_rate_RS232_trans_counter[2] ,
       \baud_rate_RS232_trans_counter[1] ,
       \baud_rate_RS232_trans_counter[0] }), .CI (1'b1), .Z
       ({UNCONNECTED, n_180, n_181, n_182, n_183, n_184, n_185, n_186,
       n_187, n_188, n_189, n_190, n_191, n_192, n_193, UNCONNECTED0}));
  increment_unsigned_204 inc_add_86_61(.A
       ({\baud_rate_RS232_counter[14] , \baud_rate_RS232_counter[13] ,
       \baud_rate_RS232_counter[12] , \baud_rate_RS232_counter[11] ,
       \baud_rate_RS232_counter[10] , \baud_rate_RS232_counter[9] ,
       \baud_rate_RS232_counter[8] , \baud_rate_RS232_counter[7] ,
       \baud_rate_RS232_counter[6] , \baud_rate_RS232_counter[5] ,
       \baud_rate_RS232_counter[4] , \baud_rate_RS232_counter[3] ,
       \baud_rate_RS232_counter[2] , \baud_rate_RS232_counter[1] ,
       \baud_rate_RS232_counter[0] }), .CI (1'b1), .Z ({UNCONNECTED1,
       n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174,
       n_175, n_176, n_177, n_178, n_179, UNCONNECTED2}));
  DFRQJIX0 \baud_rate_RS232_counter_reg[0] (.C (system_clk_i), .D
       (n_140), .Q (\baud_rate_RS232_counter[0] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[10] (.C (system_clk_i), .D
       (n_138), .Q (\baud_rate_RS232_counter[10] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[11] (.C (system_clk_i), .D
       (n_141), .Q (\baud_rate_RS232_counter[11] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[12] (.C (system_clk_i), .D
       (n_139), .Q (\baud_rate_RS232_counter[12] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[13] (.C (system_clk_i), .D
       (n_137), .Q (\baud_rate_RS232_counter[13] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[14] (.C (system_clk_i), .D
       (n_133), .Q (\baud_rate_RS232_counter[14] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[1] (.C (system_clk_i), .D
       (n_136), .Q (\baud_rate_RS232_counter[1] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[2] (.C (system_clk_i), .D
       (n_135), .Q (\baud_rate_RS232_counter[2] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[3] (.C (system_clk_i), .D
       (n_134), .Q (\baud_rate_RS232_counter[3] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[4] (.C (system_clk_i), .D
       (n_131), .Q (\baud_rate_RS232_counter[4] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[5] (.C (system_clk_i), .D
       (n_130), .Q (\baud_rate_RS232_counter[5] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[6] (.C (system_clk_i), .D
       (n_129), .Q (\baud_rate_RS232_counter[6] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[7] (.C (system_clk_i), .D
       (n_127), .Q (\baud_rate_RS232_counter[7] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[8] (.C (system_clk_i), .D
       (n_126), .Q (\baud_rate_RS232_counter[8] ));
  DFRQJIX0 \baud_rate_RS232_counter_reg[9] (.C (system_clk_i), .D
       (n_125), .Q (\baud_rate_RS232_counter[9] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[0] (.C (system_clk_i), .D
       (n_124), .Q (\baud_rate_RS232_trans_counter[0] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[10] (.C (system_clk_i),
       .D (n_122), .Q (\baud_rate_RS232_trans_counter[10] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[11] (.C (system_clk_i),
       .D (n_121), .Q (\baud_rate_RS232_trans_counter[11] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[12] (.C (system_clk_i),
       .D (n_120), .Q (\baud_rate_RS232_trans_counter[12] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[13] (.C (system_clk_i),
       .D (n_119), .Q (\baud_rate_RS232_trans_counter[13] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[14] (.C (system_clk_i),
       .D (n_118), .Q (\baud_rate_RS232_trans_counter[14] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[1] (.C (system_clk_i), .D
       (n_117), .Q (\baud_rate_RS232_trans_counter[1] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[2] (.C (system_clk_i), .D
       (n_116), .Q (\baud_rate_RS232_trans_counter[2] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[3] (.C (system_clk_i), .D
       (n_146), .Q (\baud_rate_RS232_trans_counter[3] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[4] (.C (system_clk_i), .D
       (n_148), .Q (\baud_rate_RS232_trans_counter[4] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[5] (.C (system_clk_i), .D
       (n_147), .Q (\baud_rate_RS232_trans_counter[5] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[6] (.C (system_clk_i), .D
       (n_145), .Q (\baud_rate_RS232_trans_counter[6] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[7] (.C (system_clk_i), .D
       (n_144), .Q (\baud_rate_RS232_trans_counter[7] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[8] (.C (system_clk_i), .D
       (n_143), .Q (\baud_rate_RS232_trans_counter[8] ));
  DFRQJIX0 \baud_rate_RS232_trans_counter_reg[9] (.C (system_clk_i), .D
       (n_142), .Q (\baud_rate_RS232_trans_counter[9] ));
  DFRQJIX0 \baud_rate_RS232_width_reg[10] (.C (system_clk_i), .D
       (n_34), .Q (\baud_rate_RS232_width[10] ));
  DFRJIX0 \baud_rate_RS232_width_reg[11] (.C (system_clk_i), .D (n_37),
       .Q (), .QN (\baud_rate_RS232_width[11] ));
  DFRJIX0 \baud_rate_RS232_width_reg[12] (.C (system_clk_i), .D (n_34),
       .Q (), .QN (\baud_rate_RS232_width[12] ));
  DFRJIX0 \baud_rate_RS232_width_reg[13] (.C (system_clk_i), .D (n_25),
       .Q (), .QN (\baud_rate_RS232_width[13] ));
  DFRQJIX0 \baud_rate_RS232_width_reg[14] (.C (system_clk_i), .D
       (n_36), .Q (\baud_rate_RS232_width[14] ));
  DFRQJIX0 \baud_rate_RS232_width_reg[1] (.C (system_clk_i), .D (n_33),
       .Q (\baud_rate_RS232_width[1] ));
  DFRQJIX0 \baud_rate_RS232_width_reg[2] (.C (system_clk_i), .D (n_35),
       .Q (\baud_rate_RS232_width[2] ));
  DFRQJIX0 \baud_rate_RS232_width_reg[3] (.C (system_clk_i), .D (n_38),
       .Q (\baud_rate_RS232_width[3] ));
  DFRQJIX0 \baud_rate_RS232_width_reg[4] (.C (system_clk_i), .D (n_32),
       .Q (\baud_rate_RS232_width[4] ));
  DFRJIX0 \baud_rate_RS232_width_reg[5] (.C (system_clk_i), .D (n_27),
       .Q (), .QN (\baud_rate_RS232_width[5] ));
  DFRJIX0 \baud_rate_RS232_width_reg[7] (.C (system_clk_i), .D (n_24),
       .Q (), .QN (\baud_rate_RS232_width[7] ));
  DFRJIX0 \baud_rate_RS232_width_reg[8] (.C (system_clk_i), .D (n_34),
       .Q (), .QN (\baud_rate_RS232_width[8] ));
  DFRQJIX0 \baud_rate_RS232_width_reg[9] (.C (system_clk_i), .D (n_37),
       .Q (\baud_rate_RS232_width[9] ));
  DFRQJIX0 baud_rate_br_o_reg(.C (system_clk_i), .D (n_156), .Q
       (baud_rate_br_o));
  DFRQJIX0 baud_rate_br_trans_o_reg(.C (system_clk_i), .D (n_157), .Q
       (baud_rate_br_trans_o));
  DFRQJIX0 baud_rate_cm_o_reg(.C (system_clk_i), .D (n_22), .Q
       (baud_rate_cm_o));
  SDFRQJIX0 \baud_rate_counter_reg[0] (.C (system_clk_i), .D (n_107),
       .SD (n_110), .SE (\baud_rate_counter[0] ), .Q
       (\baud_rate_counter[0] ));
  DFRQJIX0 \baud_rate_counter_reg[1] (.C (system_clk_i), .D (n_154), .Q
       (\baud_rate_counter[1] ));
  SDFRQJIX0 \baud_rate_counter_reg[2] (.C (system_clk_i), .D (n_123),
       .SD (n_113), .SE (\baud_rate_counter[2] ), .Q
       (\baud_rate_counter[2] ));
  SDFRQJIX0 \baud_rate_counter_reg[3] (.C (system_clk_i), .D (n_152),
       .SD (n_150), .SE (\baud_rate_counter[3] ), .Q
       (\baud_rate_counter[3] ));
  DFRQJIX0 \baud_rate_counter_reg[4] (.C (system_clk_i), .D (n_159), .Q
       (\baud_rate_counter[4] ));
  DFRQJIX0 baud_rate_machine_cycle_start_reg(.C (system_clk_i), .D
       (n_16), .Q (baud_rate_machine_cycle_start));
  DFRQJIX0 baud_rate_mode_2_start_reg(.C (system_clk_i), .D (n_161), .Q
       (n_162));
  DFRQJIX0 baud_rate_mode_2_work_reg(.C (system_clk_i), .D (n_160), .Q
       (n_163));
  DFRQJIX0 \baud_rate_trans_counter_reg[0] (.C (system_clk_i), .D
       (n_151), .Q (\baud_rate_trans_counter[0] ));
  DFRQJIX0 \baud_rate_width_reg[0] (.C (system_clk_i), .D
       (system_rst_i_b), .Q (\baud_rate_width[0] ));
  DFRQJIX0 \baud_rate_width_reg[1] (.C (system_clk_i), .D (n_14), .Q
       (\baud_rate_width[1] ));
  DFRQJIX0 \baud_rate_width_reg[2] (.C (system_clk_i), .D (n_14), .Q
       (\baud_rate_width[2] ));
  DFRQJIX0 \baud_rate_width_reg[3] (.C (system_clk_i), .D (n_14), .Q
       (\baud_rate_width[3] ));
  DFRJIX0 \baud_rate_width_reg[4] (.C (system_clk_i), .D (n_14), .Q (),
       .QN (\baud_rate_width[4] ));
  DFRQJIX0 \baud_rate_width_reg[5] (.C (system_clk_i), .D (n_18), .Q
       (\baud_rate_width[5] ));
  NO2JIX0 g5188(.A (n_158), .B (n_13), .Q (n_161));
  AO311JIX0 g5189(.A (n_0), .B (n_162), .C (n_128), .D (n_13), .E
       (n_17), .Q (n_160));
  AO32JIX0 g5192(.A (\baud_rate_counter[3] ), .B (n_1), .C (n_152), .D
       (\baud_rate_counter[4] ), .E (n_155), .Q (n_159));
  AN21JIX0 g5193(.A (n_153), .B (n_162), .C
       (baud_rate_clear_counter_i), .Q (n_158));
  AN21JIX0 g5197(.A (n_153), .B (n_132), .C (n_13), .Q (n_157));
  NO2JIX0 g5200(.A (n_149), .B (n_23), .Q (n_156));
  ON211JIX0 g5201(.A (n_100), .B (\baud_rate_counter[3] ), .C (n_114),
       .D (n_103), .Q (n_155));
  AO32JIX0 g5202(.A (\baud_rate_counter[0] ), .B (n_4), .C (n_107), .D
       (\baud_rate_counter[1] ), .E (n_115), .Q (n_154));
  INJIX0 g5203(.A (n_128), .Q (n_153));
  AND2JIX0 g5234(.A (n_123), .B (\baud_rate_counter[2] ), .Q (n_152));
  NO2JIX0 g5235(.A (n_112), .B (n_13), .Q (n_151));
  NA2JIX0 g5236(.A (n_114), .B (n_103), .Q (n_150));
  EO2JIX0 g5237(.A (n_111), .B (baud_rate_br_o), .Q (n_149));
  NO2I1JIX0 g5238(.B (n_106), .AN (n_190), .Q (n_148));
  NO2I1JIX0 g5239(.B (n_106), .AN (n_189), .Q (n_147));
  NO2I1JIX0 g5240(.B (n_106), .AN (n_191), .Q (n_146));
  NO2I1JIX0 g5241(.B (n_106), .AN (n_188), .Q (n_145));
  NO2I1JIX0 g5242(.B (n_106), .AN (n_187), .Q (n_144));
  NO2I1JIX0 g5243(.B (n_106), .AN (n_186), .Q (n_143));
  NO2I1JIX0 g5244(.B (n_106), .AN (n_185), .Q (n_142));
  AND2JIX0 g5245(.A (n_169), .B (n_110), .Q (n_141));
  NO2I1JIX0 g5246(.B (\baud_rate_RS232_counter[0] ), .AN (n_110), .Q
       (n_140));
  AND2JIX0 g5247(.A (n_168), .B (n_110), .Q (n_139));
  AND2JIX0 g5248(.A (n_170), .B (n_110), .Q (n_138));
  AND2JIX0 g5249(.A (n_167), .B (n_110), .Q (n_137));
  AND2JIX0 g5250(.A (n_110), .B (n_179), .Q (n_136));
  AND2JIX0 g5251(.A (n_110), .B (n_178), .Q (n_135));
  AND2JIX0 g5252(.A (n_110), .B (n_177), .Q (n_134));
  AND2JIX0 g5253(.A (n_166), .B (n_110), .Q (n_133));
  NA2I1JIX0 g5254(.B (baud_rate_br_trans_o), .AN (n_108), .Q (n_132));
  AND2JIX0 g5255(.A (n_110), .B (n_176), .Q (n_131));
  AND2JIX0 g5256(.A (n_110), .B (n_175), .Q (n_130));
  AND2JIX0 g5257(.A (n_110), .B (n_174), .Q (n_129));
  NO2I1JIX0 g5258(.B (baud_rate_br_trans_o), .AN (n_108), .Q (n_128));
  AND2JIX0 g5259(.A (n_110), .B (n_173), .Q (n_127));
  AND2JIX0 g5260(.A (n_110), .B (n_172), .Q (n_126));
  AND2JIX0 g5261(.A (n_110), .B (n_171), .Q (n_125));
  NO2JIX0 g5262(.A (n_106), .B (\baud_rate_RS232_trans_counter[0] ), .Q
       (n_124));
  NO2I1JIX0 g5263(.B (n_12), .AN (n_107), .Q (n_123));
  NO2I1JIX0 g5264(.B (n_106), .AN (n_184), .Q (n_122));
  NO2I1JIX0 g5265(.B (n_106), .AN (n_183), .Q (n_121));
  NO2I1JIX0 g5266(.B (n_106), .AN (n_182), .Q (n_120));
  NO2I1JIX0 g5267(.B (n_106), .AN (n_181), .Q (n_119));
  NO2I1JIX0 g5268(.B (n_106), .AN (n_180), .Q (n_118));
  NO2I1JIX0 g5269(.B (n_106), .AN (n_193), .Q (n_117));
  NO2I1JIX0 g5270(.B (n_106), .AN (n_192), .Q (n_116));
  ON21JIX0 g5271(.A (n_100), .B (\baud_rate_counter[0] ), .C (n_109),
       .Q (n_115));
  INJIX0 g5272(.A (n_114), .Q (n_113));
  AN21JIX0 g5273(.A (n_99), .B (n_12), .C (n_110), .Q (n_114));
  MU2IJIX0 g5274(.S (n_104), .IN0 (n_72), .IN1
       (\baud_rate_trans_counter[0] ), .Q (n_112));
  NA2I1JIX0 g5275(.B (n_98), .AN (n_105), .Q (n_111));
  INJIX0 g5276(.A (n_110), .Q (n_109));
  NO2I1JIX0 g5277(.B (n_23), .AN (n_105), .Q (n_110));
  NO2JIX0 g5278(.A (n_104), .B (n_72), .Q (n_108));
  NO2JIX0 g5279(.A (n_100), .B (n_105), .Q (n_107));
  NA2JIX0 g5280(.A (n_104), .B (n_14), .Q (n_106));
  AN321JIX0 g5281(.A (\baud_rate_RS232_counter[13] ), .B
       (\baud_rate_RS232_width[13] ), .C (n_51), .D (n_78), .E (n_87),
       .F (n_101), .Q (n_105));
  AN321JIX0 g5282(.A (\baud_rate_RS232_trans_counter[13] ), .B
       (\baud_rate_RS232_width[13] ), .C (n_50), .D (n_80), .E (n_86),
       .F (n_102), .Q (n_104));
  OR2JIX0 g5283(.A (n_100), .B (\baud_rate_counter[2] ), .Q (n_103));
  ON321JIX0 g5284(.A (n_63), .B (n_79), .C (n_97), .D (n_58), .E
       (n_70), .F (n_55), .Q (n_102));
  ON321JIX0 g5285(.A (n_62), .B (n_77), .C (n_96), .D (n_57), .E
       (n_71), .F (n_45), .Q (n_101));
  INJIX0 g5286(.A (n_99), .Q (n_100));
  NO2JIX0 g5287(.A (n_98), .B (n_23), .Q (n_99));
  ON321JIX0 g5288(.A (n_85), .B (n_88), .C (n_94), .D (n_94), .E
       (n_95), .F (n_93), .Q (n_98));
  ON221JIX0 g5289(.A (\baud_rate_RS232_trans_counter[6] ), .B (n_92),
       .C (\baud_rate_RS232_trans_counter[7] ), .D
       (\baud_rate_RS232_width[7] ), .E (n_47), .Q (n_97));
  ON221JIX0 g5290(.A (\baud_rate_RS232_counter[6] ), .B (n_91), .C
       (\baud_rate_RS232_counter[7] ), .D (\baud_rate_RS232_width[7] ),
       .E (n_46), .Q (n_96));
  AN32JIX0 g5291(.A (\baud_rate_counter[2] ), .B (n_64), .C (n_89), .D
       (\baud_rate_counter[3] ), .E (n_82), .Q (n_95));
  NO2JIX0 g5292(.A (n_90), .B (\baud_rate_counter[4] ), .Q (n_94));
  NA2JIX0 g5293(.A (n_90), .B (\baud_rate_counter[4] ), .Q (n_93));
  AO222JIX0 g5294(.A (n_40), .B (n_73), .C (n_40), .D (n_83), .E
       (\baud_rate_RS232_width[5] ), .F
       (\baud_rate_RS232_trans_counter[5] ), .Q (n_92));
  AO222JIX0 g5295(.A (n_42), .B (n_76), .C (n_42), .D (n_84), .E
       (\baud_rate_RS232_width[5] ), .F (\baud_rate_RS232_counter[5] ),
       .Q (n_91));
  EO2JIX0 g5296(.A (n_81), .B (\baud_rate_width[5] ), .Q (n_90));
  INJIX0 g5297(.A (n_88), .Q (n_89));
  NO2JIX0 g5298(.A (n_82), .B (\baud_rate_counter[3] ), .Q (n_88));
  ON222JIX0 g5299(.A (\baud_rate_RS232_width[9] ), .B (n_66), .C
       (n_62), .D (n_74), .E (n_9), .F (\baud_rate_RS232_width[10] ),
       .Q (n_87));
  ON222JIX0 g5300(.A (\baud_rate_RS232_width[9] ), .B (n_67), .C
       (n_63), .D (n_75), .E (n_7), .F (\baud_rate_RS232_width[10] ),
       .Q (n_86));
  ON222JIX0 g5301(.A (n_30), .B (n_41), .C (\baud_rate_counter[2] ), .D
       (n_64), .E (n_31), .F (\baud_rate_counter[1] ), .Q (n_85));
  AN211JIX0 g5302(.A (n_65), .B (\baud_rate_RS232_width[1] ), .C
       (n_53), .D (n_69), .Q (n_84));
  AN211JIX0 g5303(.A (n_61), .B (\baud_rate_RS232_width[1] ), .C
       (n_54), .D (n_68), .Q (n_83));
  OA21JIX0 g5304(.A (n_52), .B (\baud_rate_width[4] ), .C (n_81), .Q
       (n_82));
  NA2JIX0 g5305(.A (n_52), .B (\baud_rate_width[4] ), .Q (n_81));
  INJIX0 g5306(.A (n_79), .Q (n_80));
  ON211JIX0 g5307(.A (\baud_rate_RS232_width[11] ), .B
       (\baud_rate_RS232_trans_counter[11] ), .C (n_59), .D (n_50), .Q
       (n_79));
  INJIX0 g5308(.A (n_77), .Q (n_78));
  ON211JIX0 g5309(.A (\baud_rate_RS232_width[11] ), .B
       (\baud_rate_RS232_counter[11] ), .C (n_60), .D (n_51), .Q
       (n_77));
  ON32JIX0 g5310(.A (\baud_rate_RS232_width[3] ), .B (n_10), .C (n_53),
       .D (\baud_rate_RS232_width[4] ), .E (n_11), .Q (n_76));
  AN32JIX0 g5311(.A (\baud_rate_RS232_trans_counter[7] ), .B
       (\baud_rate_RS232_width[7] ), .C (n_47), .D
       (\baud_rate_RS232_trans_counter[8] ), .E
       (\baud_rate_RS232_width[8] ), .Q (n_75));
  AN32JIX0 g5312(.A (\baud_rate_RS232_counter[7] ), .B
       (\baud_rate_RS232_width[7] ), .C (n_46), .D
       (\baud_rate_RS232_counter[8] ), .E (\baud_rate_RS232_width[8] ),
       .Q (n_74));
  ON32JIX0 g5313(.A (\baud_rate_RS232_width[3] ), .B (n_3), .C (n_54),
       .D (\baud_rate_RS232_width[4] ), .E (n_6), .Q (n_73));
  NO2JIX0 g5314(.A (n_56), .B (\baud_rate_trans_counter[0] ), .Q
       (n_72));
  NA2JIX0 g5315(.A (n_60), .B (n_51), .Q (n_71));
  NA2JIX0 g5316(.A (n_59), .B (n_50), .Q (n_70));
  AO22JIX0 g5317(.A (n_10), .B (\baud_rate_RS232_width[3] ), .C (n_5),
       .D (\baud_rate_RS232_width[2] ), .Q (n_69));
  AO22JIX0 g5318(.A (n_3), .B (\baud_rate_RS232_width[3] ), .C (n_8),
       .D (\baud_rate_RS232_width[2] ), .Q (n_68));
  NA2JIX0 g5319(.A (n_49), .B (\baud_rate_RS232_trans_counter[9] ), .Q
       (n_67));
  NA2JIX0 g5320(.A (n_48), .B (\baud_rate_RS232_counter[9] ), .Q
       (n_66));
  AN21JIX0 g5321(.A (n_44), .B (\baud_rate_RS232_counter[2] ), .C
       (\baud_rate_RS232_counter[1] ), .Q (n_65));
  AN21JIX0 g5322(.A (n_29), .B (\baud_rate_width[3] ), .C (n_52), .Q
       (n_64));
  ON21JIX0 g5323(.A (n_43), .B (\baud_rate_RS232_trans_counter[9] ), .C
       (n_49), .Q (n_63));
  ON21JIX0 g5324(.A (n_43), .B (\baud_rate_RS232_counter[9] ), .C
       (n_48), .Q (n_62));
  AN21JIX0 g5325(.A (n_44), .B (\baud_rate_RS232_trans_counter[2] ), .C
       (\baud_rate_RS232_trans_counter[1] ), .Q (n_61));
  OA22JIX0 g5326(.A (\baud_rate_RS232_width[12] ), .B
       (\baud_rate_RS232_counter[12] ), .C (\baud_rate_RS232_width[13]
       ), .D (\baud_rate_RS232_counter[13] ), .Q (n_60));
  OA22JIX0 g5327(.A (\baud_rate_RS232_width[12] ), .B
       (\baud_rate_RS232_trans_counter[12] ), .C
       (\baud_rate_RS232_width[13] ), .D
       (\baud_rate_RS232_trans_counter[13] ), .Q (n_59));
  AN22JIX0 g5328(.A (\baud_rate_RS232_width[12] ), .B
       (\baud_rate_RS232_trans_counter[12] ), .C
       (\baud_rate_RS232_width[11] ), .D
       (\baud_rate_RS232_trans_counter[11] ), .Q (n_58));
  AN22JIX0 g5329(.A (\baud_rate_RS232_width[12] ), .B
       (\baud_rate_RS232_counter[12] ), .C (\baud_rate_RS232_width[11]
       ), .D (\baud_rate_RS232_counter[11] ), .Q (n_57));
  EN2JIX0 g5330(.A (n_39), .B (\baud_rate_width[5] ), .Q (n_56));
  NA2I1JIX0 g5332(.B (\baud_rate_RS232_trans_counter[14] ), .AN
       (\baud_rate_RS232_width[14] ), .Q (n_55));
  AND2JIX0 g5333(.A (n_6), .B (\baud_rate_RS232_width[4] ), .Q (n_54));
  AND2JIX0 g5334(.A (n_11), .B (\baud_rate_RS232_width[4] ), .Q (n_53));
  NO2JIX0 g5335(.A (n_29), .B (\baud_rate_width[3] ), .Q (n_52));
  NA2I1JIX0 g5336(.B (\baud_rate_RS232_width[14] ), .AN
       (\baud_rate_RS232_counter[14] ), .Q (n_51));
  NA2I1JIX0 g5337(.B (\baud_rate_RS232_width[14] ), .AN
       (\baud_rate_RS232_trans_counter[14] ), .Q (n_50));
  NA2JIX0 g5338(.A (n_7), .B (\baud_rate_RS232_width[10] ), .Q (n_49));
  NA2JIX0 g5339(.A (n_9), .B (\baud_rate_RS232_width[10] ), .Q (n_48));
  OR2JIX0 g5340(.A (\baud_rate_RS232_width[8] ), .B
       (\baud_rate_RS232_trans_counter[8] ), .Q (n_47));
  OR2JIX0 g5341(.A (\baud_rate_RS232_width[8] ), .B
       (\baud_rate_RS232_counter[8] ), .Q (n_46));
  NA2I1JIX0 g5342(.B (\baud_rate_RS232_counter[14] ), .AN
       (\baud_rate_RS232_width[14] ), .Q (n_45));
  INJIX0 g5345(.A (\baud_rate_RS232_width[2] ), .Q (n_44));
  INJIX0 g5350(.A (\baud_rate_RS232_width[9] ), .Q (n_43));
  OR2JIX0 g5354(.A (\baud_rate_RS232_width[5] ), .B
       (\baud_rate_RS232_counter[5] ), .Q (n_42));
  AND2JIX0 g5355(.A (n_31), .B (\baud_rate_counter[1] ), .Q (n_41));
  OR2JIX0 g5356(.A (\baud_rate_RS232_width[5] ), .B
       (\baud_rate_RS232_trans_counter[5] ), .Q (n_40));
  NA3I1JIX0 g5357(.B (n_26), .C (\baud_rate_width[3] ), .AN
       (\baud_rate_width[4] ), .Q (n_39));
  AO21JIX0 g5358(.A (n_24), .B (baud_rate_scon_sm1_i), .C (n_36), .Q
       (n_38));
  OR2JIX0 g5363(.A (n_25), .B (n_24), .Q (n_37));
  NO2I1JIX0 g5364(.B (baud_rate_scon_sm2_i), .AN (n_25), .Q (n_36));
  AND2JIX0 g5365(.A (n_25), .B (baud_rate_scon_sm2_i), .Q (n_35));
  OR2JIX0 g5366(.A (n_25), .B (n_27), .Q (n_34));
  AND2JIX0 g5367(.A (n_27), .B (baud_rate_scon_sm1_i), .Q (n_33));
  AO21JIX0 g5368(.A (n_19), .B (baud_rate_scon_sm1_i), .C (n_24), .Q
       (n_32));
  AO21JIX0 g5369(.A (n_21), .B (n_20), .C (\baud_rate_counter[0] ), .Q
       (n_31));
  AN21JIX0 g5370(.A (n_21), .B (\baud_rate_width[2] ), .C (n_28), .Q
       (n_30));
  INJIX0 g5371(.A (n_29), .Q (n_28));
  OR2JIX0 g5372(.A (n_21), .B (\baud_rate_width[2] ), .Q (n_29));
  NO2I1JIX0 g5373(.B (baud_rate_scon_sm2_i), .AN (n_19), .Q (n_27));
  NO2I1JIX0 g5374(.B (n_20), .AN (\baud_rate_width[2] ), .Q (n_26));
  NO2I1JIX0 g5375(.B (baud_rate_scon_sm1_i), .AN (n_19), .Q (n_25));
  AND2JIX0 g5376(.A (n_19), .B (baud_rate_scon_sm2_i), .Q (n_24));
  ON21JIX0 g5377(.A (n_17), .B (n_2), .C (system_rst_i_b), .Q (n_23));
  AN21JIX0 g5378(.A (baud_rate_cm_o), .B
       (baud_rate_machine_cycle_start), .C (n_15), .Q (n_22));
  OR2JIX0 g5380(.A (\baud_rate_width[0] ), .B (\baud_rate_width[1] ),
       .Q (n_21));
  NA2JIX0 g5381(.A (\baud_rate_width[1] ), .B (\baud_rate_width[0] ),
       .Q (n_20));
  AND2JIX0 g5382(.A (n_18), .B (baud_rate_pcon_rs232_i), .Q (n_19));
  NO2JIX0 g5388(.A (n_13), .B (baud_rate_pcon_smod_i), .Q (n_18));
  NO3I1JIX0 g5389(.B (n_162), .C (baud_rate_clear_counter_i), .AN
       (n_163), .Q (n_17));
  INJIX0 g5391(.A (n_15), .Q (n_16));
  NA2JIX0 g5392(.A (baud_rate_start_cm_i), .B (system_rst_i_b), .Q
       (n_15));
  INJIX0 g5393(.A (n_13), .Q (n_14));
  NA2JIX0 g5394(.A (system_rst_i_b), .B (baud_rate_scon_sm0_i), .Q
       (n_13));
  NA2JIX0 g5395(.A (\baud_rate_counter[1] ), .B (\baud_rate_counter[0]
       ), .Q (n_12));
  INJIX0 g5396(.A (\baud_rate_RS232_counter[4] ), .Q (n_11));
  INJIX0 g5397(.A (\baud_rate_RS232_counter[3] ), .Q (n_10));
  INJIX0 g5398(.A (\baud_rate_RS232_counter[10] ), .Q (n_9));
  INJIX0 g5399(.A (\baud_rate_RS232_trans_counter[2] ), .Q (n_8));
  INJIX0 g5400(.A (\baud_rate_RS232_trans_counter[10] ), .Q (n_7));
  INJIX0 g5401(.A (\baud_rate_RS232_trans_counter[4] ), .Q (n_6));
  INJIX0 g5402(.A (\baud_rate_RS232_counter[2] ), .Q (n_5));
  INJIX0 g5403(.A (\baud_rate_counter[1] ), .Q (n_4));
  INJIX0 g5404(.A (\baud_rate_RS232_trans_counter[3] ), .Q (n_3));
  INJIX0 g5405(.A (baud_rate_scon_sm0_i), .Q (n_2));
  INJIX0 g5406(.A (\baud_rate_counter[4] ), .Q (n_1));
  INJIX0 g5407(.A (baud_rate_clear_counter_i), .Q (n_0));
endmodule

